[project]
id = "github.com/wei840222/jsrun"
name = "jsrun"
version = "0.1.0"
authors = [
    "wei840222@gmail.com"
]
source-url = "https://github.com/wei840222/jsrun"

[build]
exclude = [
    "/web/node_modules"
]